export const CLUSTER_COLOR = "#6366f1";
export const WORD_COLOR = "#94a3b8";
export const HOVERED_COLOR = "#f59e0b";
export const SELECTED_COLOR = "#10b981";
export const EDGE_COLOR = "#334155";

/**
 * Seed palette of 10 perceptually distinct colors.
 * Source: https://coolors.co/palette/669900-99cc33-ccee66-006699-3399cc-990066-cc3399-ff6600-ff9900-ffcc00
 */
export const DISTINCT_PALETTE: readonly string[] = [
  "#669900",
  "#99cc33",
  "#ccee66",
  "#006699",
  "#3399cc",
  "#990066",
  "#cc3399",
  "#ff6600",
  "#ff9900",
  "#ffcc00",
] as const;

/**
 * Return a visually distinct color for a given index.
 *
 * For indices within the seed palette range, the palette color is returned
 * directly. Beyond that, new colors are generated by rotating hue evenly
 * across the color wheel using the golden-angle spacing technique, which
 * maximises perceptual separation between successive colors.
 *
 * Saturation and lightness are held in a range that remains legible on
 * the dark graph background.
 */
export function distinctColor(index: number): string {
  const i = Math.max(0, Math.floor(index));
  if (i < DISTINCT_PALETTE.length) return DISTINCT_PALETTE[i];

  // Golden-angle hue spacing gives maximum separation between successive values
  const GOLDEN_ANGLE = 137.508; // degrees
  const hue = (i * GOLDEN_ANGLE) % 360;
  const saturation = 70 + (i % 3) * 10; // 70 / 80 / 90
  const lightness = 50 + (i % 2) * 10; // 50 / 60
  return `hsl(${Math.round(hue)}, ${saturation}%, ${lightness}%)`;
}

export function importanceToColor(importance: number): string {
  const h = Math.round(220 + importance * 40);
  const s = Math.round(60 + importance * 30);
  const l = Math.round(65 - importance * 20);
  return `hsl(${h}, ${s}%, ${l}%)`;
}
